name: CD Pipeline

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only deploy if CI workflow completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build & push Docker images (only on main branch)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest ./back
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest

      - name: Build & push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest ./front
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest
