name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for SonarCloud PR analysis

      # Setup Java for backend
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      # Setup Node for frontend
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Build & test backend (Spring Boot + JaCoCo)
      - name: Build & test backend
        run: mvn -f back/pom.xml clean verify

      # Build & test frontend (Angular + Karma + lcov)
      - name: Build & test frontend
        run: |
          cd front
          npm install
          npm test -- --watch=false --code-coverage

      # Run SonarCloud analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build & push Docker images
      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push backend Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest ./back
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest

      - name: Build & push frontend Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest ./front
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest
